In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("exasens.csv")
dataset.dropna(inplace = True)
dataset.isnull().sum()
dataset

,Diagnosis,ID,Imagery_part_min,Imagery_part_avg,Real_part_min,Real_part_avg,Gender,Age,Smoking
0,COPD,301-4,-320.61,-300.563531,-495.26,-464.171991,1,77,2
1,COPD,302-3,-325.39,-314.750360,-473.73,-469.263140,0,72,2
2,COPD,303-3,-323.00,-317.436056,-476.12,-471.897667,1,73,3
3,COPD,304-4,-327.78,-317.399670,-473.73,-468.856388,1,76,2
4,COPD,305-4,-325.39,-316.155785,-478.52,-472.869783,0,65,2
...,...,...,...,...,...,...,...,...,...
366,Infected,148-5,-323.00,-314.384434,-476.12,-472.103689,1,38,1
367,Infected,149-5,-323.00,-314.323628,-476.12,-472.395413,1,36,1
368,Infected,150-5,-323.00,-312.856656,-480.91,-472.294281,0,33,1
369,Infected,151-4,-327.78,-319.305447,-476.12,-471.776918,1,43,1


In [3]:

X = dataset.iloc[:,2:8].values
y = dataset.iloc[:,0].values

In [4]:
dataset.shape

(100, 9)

In [5]:
dataset.dtypes

Diagnosis            object
ID                   object
Imagery_part_min    float64
Imagery_part_avg    float64
Real_part_min       float64
Real_part_avg       float64
Gender                int64
Age                   int64
Smoking               int64
dtype: object

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 2)
print(type(X_train))
print(type(y_train))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [7]:
print(X_train)

[[-332.57      -319.0374144 -473.73      -463.2120865    0.
    54.       ]
 [-315.82      -294.2698616 -471.34      -463.1934272    0.
    56.       ]
 [-320.61      -311.658041  -473.73      -469.729237     0.
    76.       ]
 [-320.61      -302.6182807 -468.95      -464.8477558    0.
    21.       ]
 [-327.78      -318.792207  -478.52      -473.7268171    1.
    18.       ]
 [-327.78      -318.6775535 -507.23      -469.0241943    1.
    60.       ]
 [-231.        -231.        -441.        -441.           1.
    73.       ]
 [-330.18      -320.9939204 -466.55      -459.6267977    1.
    18.       ]
 [-337.35      -328.2809854 -500.05      -466.9809668    1.
    20.       ]
 [-323.        -313.0565374 -473.73      -468.5672198    1.
    27.       ]
 [-320.61      -311.8019294 -500.05      -468.0027422    1.
    46.       ]
 [-325.39      -314.7503595 -473.73      -469.2631404    0.
    72.       ]
 [-228.        -228.        -442.        -442.           1.
    75.       ]
 [-323.     

In [8]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 200, 
                                    criterion = 'gini', 
                                    random_state = 3,
                                    max_depth=20)
classifier.fit(X_train, y_train)

RandomForestClassifier(max_depth=20, n_estimators=200, random_state=3)

In [9]:
y_pred = classifier.predict(X_test)

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
am = accuracy_score(y_test, y_pred)
print (am)
from sklearn.metrics import confusion_matrix,classification_report
print(classification_report(y_test,y_pred))

[[ 0  0  0  1]
 [ 1 12  0  0]
 [ 0  0  4  0]
 [ 0  0  1  1]]
0.85
              precision    recall  f1-score   support

      Asthma       0.00      0.00      0.00         1
        COPD       1.00      0.92      0.96        13
          HC       0.80      1.00      0.89         4
    Infected       0.50      0.50      0.50         2

    accuracy                           0.85        20
   macro avg       0.57      0.61      0.59        20
weighted avg       0.86      0.85      0.85        20

